/**
 * Definição das 34 perguntas do questionário.
 * Exportado como constante para uso no agente respondedor e no exportador.
 */

export const PERGUNTAS = [
  {
    id: 'P1',
    bloco: 1,
    texto: 'Quantos anos você tem?',
    tipo: 'escolha_unica',
    opcoes: ['8 ou 9 anos', '10 ou 11 anos', '12 ou 13 anos', '14 ou 15 anos'],
  },
  {
    id: 'P2',
    bloco: 1,
    texto: 'Com que frequência você usa o portal da escola?',
    tipo: 'escolha_unica',
    opcoes: ['Nunca usei', 'Já usei algumas vezes', 'Uso toda semana', 'Uso quase todo dia'],
  },
  {
    id: 'P3',
    bloco: 1,
    texto: 'Em qual aparelho você mais usa o portal?',
    tipo: 'escolha_unica',
    opcoes: ['Celular', 'Computador ou notebook', 'Tablet', 'Uso em aparelhos diferentes, depende do dia'],
  },
  {
    id: 'P4',
    bloco: 1,
    texto: 'Onde você costuma usar o portal?',
    tipo: 'escolha_unica',
    opcoes: ['Só na escola', 'Só em casa', 'Tanto na escola quanto em casa', 'Em outros lugares também (biblioteca, casa de amigo…)'],
  },
  {
    id: 'P5',
    bloco: 1,
    texto: 'Quando você não sabe como usar uma parte do portal, o que você faz?',
    tipo: 'multipla_escolha',
    opcoes: ['Fico tentando sozinho até descobrir', 'Peço ajuda para um colega', 'Peço ajuda para o professor', 'Peço ajuda para alguém em casa', 'Desisto e não uso aquela parte', 'Procuro um vídeo ou tutorial'],
  },
  {
    id: 'P6',
    bloco: 2,
    texto: 'Quando você abre o portal, o que aparece primeiro para você?',
    tipo: 'multipla_escolha',
    opcoes: ['Uma lista de matérias ou disciplinas', 'Atividades ou tarefas para fazer', 'Vídeos ou conteúdos para assistir', 'Notícias ou avisos da escola', 'Não sei bem o que aparece, é confuso', 'Nunca prestei atenção nisso'],
  },
  {
    id: 'P7',
    bloco: 2,
    texto: 'Quando você abre o portal, como você se sente?',
    tipo: 'emoji',
    opcoes: ['😃 Animado, sei o que vou fazer', '🙂 Tranquilo, vou descobrindo', '😐 Normal, nem bom nem ruim', '😕 Um pouco perdido', '😤 Frustrado, não entendo nada'],
  },
  {
    id: 'P8',
    bloco: 2,
    texto: 'O portal deixa claro o que você pode fazer nele?',
    tipo: 'likert',
    opcoes: ['Sim, muito claro', 'Mais ou menos claro', 'Não muito claro', 'Não, é bem confuso'],
  },
  {
    id: 'P9',
    bloco: 2,
    texto: 'Tem alguma coisa que você acha que existe no portal mas nunca conseguiu encontrar?',
    tipo: 'aberta',
  },
  {
    id: 'P10',
    bloco: 2,
    texto: 'Quando você olha para o menu do portal, o que você acha?',
    tipo: 'multipla_escolha',
    opcoes: ['É fácil de entender', 'Tem muitas opções e fico confuso', 'Não uso o menu, prefiro clicar em outras coisas', 'Não sei onde fica o menu', 'Já me acostumei, mas no começo era difícil'],
  },
  {
    id: 'P11',
    bloco: 2,
    texto: 'Comparando com outros apps ou sites que você usa (YouTube, jogos, redes sociais), como é o portal da sua escola?',
    tipo: 'likert',
    opcoes: ['Muito mais fácil de usar', 'Um pouco mais fácil', 'Mais ou menos igual', 'Um pouco mais difícil', 'Muito mais difícil de usar'],
  },
  {
    id: 'P12',
    bloco: 3,
    texto: 'Quando você quer achar alguma coisa no portal, o que você faz primeiro?',
    tipo: 'escolha_unica',
    opcoes: ['Uso a barra de busca (aquela caixinha para digitar)', 'Fico clicando nos menus até achar', 'Vou direto em uma parte que já conheço', 'Peço para alguém me mostrar onde fica', 'Não sei, fico perdido'],
  },
  {
    id: 'P13',
    bloco: 3,
    texto: 'Você consegue usar a busca do portal para encontrar o que quer?',
    tipo: 'likert',
    opcoes: ['Sempre encontro o que procuro', 'Na maioria das vezes encontro', 'Às vezes encontro, às vezes não', 'Quase nunca encontro', 'Nunca tentei usar a busca'],
  },
  {
    id: 'P14',
    bloco: 3,
    texto: 'Se o portal tivesse as coisas separadas em categorias, qual dessas você acharia mais útil?',
    tipo: 'multipla_escolha',
    opcoes: ['Aulas (videoaulas, explicações)', 'Atividades (exercícios, tarefas)', 'Recursos (materiais extras, apostilas, PDFs)', 'Trilhas (sequências de conteúdo para seguir)', 'Jogos e desafios', 'Não importa, desde que seja fácil de achar'],
  },
  {
    id: 'P15',
    bloco: 3,
    texto: 'Cenário real: imagine que o seu professor falou sobre uma atividade de programação disponível no portal. Como você faria para achar essa atividade?',
    tipo: 'aberta',
  },
  {
    id: 'P16',
    bloco: 3,
    texto: 'O menu do portal fica no topo da tela (barra horizontal) ou na lateral (barra vertical, como uma gaveta). Qual você prefere?',
    tipo: 'escolha_unica',
    opcoes: ['Prefiro no topo, já conheço assim', 'Prefiro na lateral, acho mais organizado', 'Tanto faz, o que importa é ser fácil', 'Não sei a diferença'],
  },
  {
    id: 'P17',
    bloco: 3,
    texto: 'Quando você está dentro de uma página do portal e quer ir para outra parte, o que acontece?',
    tipo: 'multipla_escolha',
    opcoes: ['Consigo navegar fácil, sei onde clicar', 'Fico procurando onde clicar por um tempo', 'Volto para o início e começo de novo', 'Uso o botão "voltar" do navegador', 'Fico perdido e às vezes fecho o portal'],
  },
  {
    id: 'P18',
    bloco: 3,
    texto: 'Já aconteceu de você clicar em algo achando que ia abrir uma coisa e não acontecer nada, ou abrir outra coisa?',
    tipo: 'likert',
    opcoes: ['Sim, acontece muito', 'Sim, já aconteceu algumas vezes', 'Raramente acontece', 'Nunca aconteceu', 'Não sei / não prestei atenção'],
  },
  {
    id: 'P19',
    bloco: 4,
    texto: 'Com que frequência você procura algo no portal e não consegue encontrar?',
    tipo: 'likert',
    opcoes: ['Sempre que uso o portal isso acontece', 'Acontece bastante', 'Acontece às vezes', 'Raramente acontece', 'Nunca acontece'],
  },
  {
    id: 'P20',
    bloco: 4,
    texto: 'Quando você não acha o que está procurando, quanto tempo você tenta antes de desistir?',
    tipo: 'escolha_unica',
    opcoes: ['Desisto quase na hora, menos de 1 minuto', 'Tento por uns 2 ou 3 minutos', 'Tento por mais de 5 minutos', 'Não desisto, fico até achar', 'Depende do quanto preciso daquilo'],
  },
  {
    id: 'P21',
    bloco: 4,
    texto: 'O que você faz quando não encontra o que precisava?',
    tipo: 'multipla_escolha',
    opcoes: ['Peço ajuda para o professor', 'Peço ajuda para um colega', 'Procuro em outro site fora do portal', 'Desisto e não faço a tarefa', 'Tento de novo mais tarde', 'Mando mensagem para alguém da escola'],
  },
  {
    id: 'P22',
    bloco: 4,
    texto: 'O que te faz desistir mais rápido de procurar algo no portal?',
    tipo: 'multipla_escolha',
    opcoes: ['Não encontro nem com a busca', 'Clico em vários lugares e não abre nada', 'A página demora para carregar', 'Não entendo os nomes das seções', 'Tem muita coisa na tela ao mesmo tempo', 'Fico indo e voltando sem saber onde estou'],
  },
  {
    id: 'P23',
    bloco: 4,
    texto: 'Quando você não acha algo no portal, como você se sente?',
    tipo: 'emoji',
    opcoes: ['😤 Com raiva, é muito difícil', '😞 Chateado, queria ter encontrado', '😐 Normal, já estou acostumado', '🤷 Indiferente, não era tão importante', '😅 Sem problema, sempre tem alguém para ajudar'],
  },
  {
    id: 'P24',
    bloco: 4,
    texto: 'Conta uma situação em que você tentou achar algo no portal e não conseguiu. O que aconteceu?',
    tipo: 'aberta',
  },
  {
    id: 'P25',
    bloco: 5,
    texto: 'Se você pudesse salvar seus recursos favoritos para achar rápido depois, você usaria?',
    tipo: 'likert',
    opcoes: ['Com certeza, usaria sempre', 'Provavelmente usaria', 'Talvez, dependeria de como funciona', 'Acho que não usaria', 'Não, prefiro procurar cada vez que precisar'],
  },
  {
    id: 'P26',
    bloco: 5,
    texto: 'Se o portal mostrasse os últimos conteúdos que você acessou, isso te ajudaria?',
    tipo: 'likert',
    opcoes: ['Sim, muito — uso muito as mesmas coisas', 'Sim, um pouco', 'Não faria diferença', 'Não, prefiro começar do zero toda vez', 'Não sei se entendi como funcionaria'],
  },
  {
    id: 'P27',
    bloco: 5,
    texto: 'Se o portal pudesse te sugerir conteúdos com base no que você já usou, o que você acharia?',
    tipo: 'escolha_unica',
    opcoes: ['Adoraria, me ajudaria a descobrir coisas novas', 'Seria útil às vezes', 'Indiferente', 'Prefiro escolher por conta própria, sem sugestões', 'Dependeria do que ele sugerisse'],
  },
  {
    id: 'P28',
    bloco: 5,
    texto: 'Das opções abaixo, quais deixariam o portal mais fácil de usar para você?',
    tipo: 'multipla_escolha',
    opcoes: ['Poder fixar atalhos rápidos na tela inicial', 'Menu lateral em vez de menu no topo', 'Conteúdos separados por tipo (aulas, atividades, recursos, trilhas)', 'Uma barra de busca mais visível e fácil de usar', 'Ver o que eu acessei recentemente', 'Indicações do que é mais usado pelos colegas', 'A tela inicial mostrar só o que é mais importante'],
  },
  {
    id: 'P29',
    bloco: 5,
    texto: 'Tem alguma coisa que você gostaria que o portal tivesse e que ele não tem hoje?',
    tipo: 'aberta',
  },
  {
    id: 'P30',
    bloco: 5,
    texto: 'Se você fosse recomendar o portal para um amigo que ainda não usa, o que você diria?',
    tipo: 'aberta',
  },
  {
    id: 'P31',
    bloco: 6,
    texto: 'No geral, como você avalia o portal da sua escola?',
    tipo: 'emoji',
    opcoes: ['⭐⭐⭐⭐⭐ Muito bom, gosto bastante', '⭐⭐⭐⭐ Bom, mas poderia melhorar', '⭐⭐⭐ Médio, tem coisas boas e ruins', '⭐⭐ Ruim, é difícil de usar', '⭐ Muito ruim, não gosto de usar'],
  },
  {
    id: 'P32',
    bloco: 6,
    texto: 'Você indicaria o portal para um colega de outra escola usar?',
    tipo: 'escolha_unica',
    opcoes: ['Sim, com certeza indicaria', 'Provavelmente indicaria', 'Talvez indicaria, talvez não', 'Provavelmente não indicaria', 'Não indicaria de jeito nenhum'],
  },
  {
    id: 'P33',
    bloco: 6,
    texto: 'Comparando com o começo do ano, o portal ficou mais fácil de usar para você?',
    tipo: 'escolha_unica',
    opcoes: ['Sim, ficou muito mais fácil', 'Um pouco mais fácil', 'Continua igual', 'Ficou até mais difícil', 'Não uso há tempo suficiente para comparar'],
  },
  {
    id: 'P34',
    bloco: 6,
    texto: 'Se você pudesse descrever o portal com apenas uma palavra, qual seria?',
    tipo: 'aberta',
  },
];
